### Downloading RA factor

In [88]:
import numpy as np
import pandas as pd
import datetime

from collections import defaultdict
import glob
import tqdm
import time

In [89]:
path_to = '..'

In [107]:
import glob
path = path_to + '/MarketData_raw/NA/'
files = glob.glob(path + '*.csv')
tickers = list(map(lambda f: f[21:-4], files))
print(' '.join(tickers[:10]))

AN8068571086 BMG491BT1088 BMG6359F1032 BMG812761002 BMG982941046 CH0044328745 CH0048265513 CH0102993182 CH0114405324 GB00B4VLR192

In [108]:
files = ['../MarketData_raw/NA\\US2441991054.csv']
tickers = ['US2441991054']

In [109]:
market_data = {}
PATH_TO_MARKET_DATA = path_to + "/MarketData_raw/NA/"   
for sym in tickers:
    market_data[sym] = pd.read_csv(PATH_TO_MARKET_DATA + sym + '.csv', parse_dates=['Date'], index_col='Date') #.loc['2017-01-01':]

In [111]:
market_data['US2441991054']

                Open     High       Low    Close
Date
2006-01-03   34.0050   34.215   33.9300   34.000
2006-01-04   34.0000   34.260   33.8050   34.045
2006-01-05   33.8250   34.155   33.8250   34.100
2006-01-06   34.2250   34.400   34.1550   34.215
2006-01-09   34.2150   34.560   34.1800   34.415
2006-01-10   34.3500   34.430   34.0100   34.430
2006-01-11   34.4300   34.705   34.1500   34.575
2006-01-12   34.6300   34.800   34.2600   34.640
2006-01-13   34.7500   34.830   34.5500   34.800
2006-01-17   34.5400   35.240   34.4900   35.195
2006-01-18   34.9750   35.265   34.9300   35.205
2006-01-19   35.3000   35.745   35.2150   35.235
2006-01-20   35.4050   35.410   34.4000   34.430
2006-01-23   34.4450   34.835   34.2550   34.600
2006-01-24   34.7150   35.585   34.6750   35.360
2006-01-25   35.3500   35.975   35.0400   35.785
2006-01-26   35.9000   36.000   35.2000   35.675
2006-01-27   35.6750   36.300   35.6000   36.200
2006-01-30   36.1250   36.280   35.8400   36.110
2006-01-31   36.1150   36.115   35.6800   35.880
2006-02-01   35.8925   37.965   34.9050   37.550
2006-02-02   37.5300   37.745   37.2600   37.370
2006-02-03   37.3800   37.505   37.0750   37.255
2006-02-06   37.2550   37.500   36.9800   37.460
2006-02-07   37.4765   37.720   37.2950   37.545
2006-02-08   37.5000   37.505   36.4000   36.785
2006-02-09   36.8030   37.290   36.6000   36.935
2006-02-10   36.9500   37.045   36.4450   36.810
2006-02-13   36.8250   37.190   36.6450   36.900
2006-02-14   36.7400   37.670   35.8500   37.335
...              ...      ...       ...      ...
2017-04-06  109.6200  110.890  109.2000  110.440
2017-04-07  110.3800  110.840  109.2900  109.320
2017-04-10  109.4500  110.210  109.1800  109.630
2017-04-11  110.0200  111.380  109.3700  111.160
2017-04-12  110.9900  111.199  109.2800  109.350
2017-04-13  109.1000  109.570  107.9600  108.000
2017-04-17  108.3900  108.990  107.7500  108.800
2017-04-18  108.0200  108.880  107.8300  108.470
2017-04-19  108.8000  108.990  107.8900  108.220
2017-04-20  108.0000  109.150  107.2600  108.800
2017-04-21  109.0400  109.470  107.0400  107.540
2017-04-24  109.0100  110.590  108.9400  110.250
2017-04-25  111.6800  114.130  111.5700  113.150
2017-04-26  113.0900  113.780  112.5000  112.550
2017-04-27  112.5000  112.680  110.5400  111.180
2017-04-28  111.0000  111.855  109.8400  111.610
2017-05-01  112.2500  112.790  111.9300  111.970
2017-05-02  112.2800  112.943  110.4200  110.930
2017-05-03  110.3400  111.000  109.7900  110.790
2017-05-04  111.0200  112.090  110.4200  112.030
2017-05-05  111.6000  113.140  111.3800  113.110
2017-05-08  112.9400  113.130  112.2200  112.640
2017-05-09  112.9600  114.040  112.8400  113.580
2017-05-10  113.5000  114.170  113.3300  113.550
2017-05-11  113.4500  114.130  112.2900  113.470
2017-05-12  113.0400  113.180  112.3700  113.110
2017-05-15  113.6200  113.970  113.2700  113.800
2017-05-16  114.1000  114.960  113.8254  114.800
2017-05-17  113.8000  114.460  113.0500  113.230
2017-05-18  112.1900  113.040  111.1200  112.310

[2864 rows x 4 columns]

In [112]:
PATH_TO_FEATURES_DATA = 'D:/data/spx_dataset_recover/reports/'
#dateparse = lambda x: datetime.datetime.strptime(str(x), '%Y-%m-%d')
#pd.read_csv(PATH_TO_FEATURES_DATA + sym + '.csv', parse_dates=["Date"], \
#                          usecols = ["Date", "Firm Name", "Target Price"])

### Target Price

In [113]:
# read features data
dateparse = lambda x: datetime.datetime.strptime(x, '%Y-%m-%d')
rec_data = defaultdict()
for nb, sym in enumerate(tickers):
    try:
        buf = pd.read_csv(PATH_TO_FEATURES_DATA + sym + '.csv', parse_dates=["Date"], date_parser=dateparse, \
                          usecols = ["Date", "Firm Name", "Target Price"])
        #buf = buf.loc[buf.Date>datetime.datetime(2017,1,1)]
        rec_data[sym] = buf[buf["Target Price"] != 0]      
    except:
        rec_data[sym] = pd.DataFrame(columns= ["Date", "Firm Name", "Target Price"])

In [114]:
rec_data['US2441991054']

           Date                    Firm Name  Target Price
3    2005-08-17                Credit Suisse          45.0
6    2005-11-18            Bear Stearns & Co          39.0
7    2005-11-23              Lehman Brothers          39.0
8    2005-11-28               Morgan Stanley          40.0
9    2005-12-01                       Stifel          38.0
10   2005-12-05                          UBS          37.0
11   2005-12-13  Prudential Equity Group Inc          41.5
12   2005-12-14                        Baird          35.5
14   2006-01-12  Prudential Equity Group Inc          41.5
16   2006-01-17              Lehman Brothers          39.0
17   2006-01-27                        Baird          39.0
18   2006-02-13            Bear Stearns & Co          40.5
19   2006-02-14               Morgan Stanley          45.0
20   2006-02-14  Prudential Equity Group Inc          41.5
21   2006-02-15                        Baird          40.0
22   2006-02-15              Lehman Brothers          47.5
23   2006-02-15                Credit Suisse          45.0
24   2006-02-15                       Stifel          42.0
25   2006-02-23  Prudential Equity Group Inc          41.5
26   2006-03-02                          UBS          38.5
27   2006-03-23                       Stifel          42.0
28   2006-03-27                Credit Suisse          51.5
29   2006-04-03                       Stifel          42.0
31   2006-04-12  Prudential Equity Group Inc          50.0
32   2006-04-18                          UBS          43.0
33   2006-04-27            Bear Stearns & Co          46.0
34   2006-04-27                       Stifel          55.5
35   2006-05-17                Credit Suisse          51.5
36   2006-05-17                          UBS          44.0
37   2006-05-17                        Baird          49.0
...         ...                          ...           ...
2592 2017-04-07                    Macquarie         102.0
2593 2017-04-10                       Stifel         126.0
2596 2017-04-10                  J.P. Morgan          90.0
2597 2017-04-10          RBC Capital Markets         109.0
2598 2017-04-11                    Jefferies         105.0
2599 2017-04-12                Credit Suisse         132.0
2601 2017-04-13                        Baird         125.0
2602 2017-04-13    Seaport Global Securities         102.0
2604 2017-04-17               Morgan Stanley          94.0
2605 2017-04-17          RBC Capital Markets         109.0
2606 2017-04-17                     Barclays          82.0
2609 2017-04-18                Piper Jaffray         106.0
2610 2017-04-20    Seaport Global Securities         102.0
2611 2017-04-24                Piper Jaffray         106.0
2613 2017-04-25          RBC Capital Markets         109.0
2615 2017-05-01          RBC Capital Markets         109.0
2616 2017-05-01                  J.P. Morgan          94.0
2617 2017-05-02                    Macquarie         102.0
2618 2017-05-03                    Macquarie         102.0
2619 2017-05-05                Piper Jaffray         106.0
2620 2017-05-05                 Evercore ISI         114.0
2621 2017-05-05    Seaport Global Securities         102.0
2626 2017-05-10          RBC Capital Markets         109.0
2627 2017-05-10                        Baird         125.0
2630 2017-05-15          RBC Capital Markets         109.0
2631 2017-05-15   Vertical Research Partners         115.0
2633 2017-05-15                  J.P. Morgan          95.0
2634 2017-05-16                        Baird         125.0
2635 2017-05-16                    Jefferies         105.0
2636 2017-05-17                  J.P. Morgan          95.0

[1933 rows x 3 columns]

In [115]:
"""    
analysts_universe = []
for ticker in list(rec_data.keys()):
    try:
        companies = np.unique(rec_data[ticker]["Firm Name"])
        for comp in companies:
            if comp not in analysts_universe:
                analysts_universe.append(comp)
    except:
        print(ticker)
  

# Count number of recommendations along the analysts
analysts_counts = pd.DataFrame(np.zeros(len(analysts_universe)), index = analysts_universe, columns=["Count"])
for ticker in list(rec_data.keys()):
    try:
        for comp in rec_data[ticker]["Firm Name"]:
            analysts_counts.loc[comp] += 1
    except:
        print(ticker)

# Reduce the data
analysts_universe = list(analysts_counts[analysts_counts["Count"] > 1].index)
print( analysts_universe)
reduced_rec_data = defaultdict()
for ticker in rec_data.keys():
    try:
        reduced_rec_data[ticker] = rec_data[ticker][rec_data[ticker]["Firm Name"].isin(analysts_universe)].copy()
    except:
        reduced_rec_data[ticker] = pd.DataFrame(columns= ["Date", "Firm Name", "Target Price"])
"""

'    \nanalysts_universe = []\nfor ticker in list(rec_data.keys()):\n    try:\n        companies = np.unique(rec_data[ticker]["Firm Name"])\n        for comp in companies:\n            if comp not in analysts_universe:\n                analysts_universe.append(comp)\n    except:\n        print(ticker)\n  \n\n# Count number of recommendations along the analysts\nanalysts_counts = pd.DataFrame(np.zeros(len(analysts_universe)), index = analysts_universe, columns=["Count"])\nfor ticker in list(rec_data.keys()):\n    try:\n        for comp in rec_data[ticker]["Firm Name"]:\n            analysts_counts.loc[comp] += 1\n    except:\n        print(ticker)\n\n# Reduce the data\nanalysts_universe = list(analysts_counts[analysts_counts["Count"] > 1].index)\nprint( analysts_universe)\nreduced_rec_data = defaultdict()\nfor ticker in rec_data.keys():\n    try:\n        reduced_rec_data[ticker] = rec_data[ticker][rec_data[ticker]["Firm Name"].isin(analysts_universe)].copy()\n    except:\n        reduced_rec_data[ticker] = pd.DataFrame(columns= ["Date", "Firm Name", "Target Price"])\n'

In [116]:
analysts_universe = ['Argus Research Corp',
 'Atlantic Equities LLP',
 'BMO Capital Markets',
 'Baird',
 'Barclays',
 'Bear Stearns & Co',
 'Bernstein',
 'Canaccord Genuity',
 'Capital One Securities, Inc.',
 'Clarksons Platou Securities AS',
 'Clarksons Platou Securities Inc',
 'Cowen',
 'Credit Suisse',
 'D.A. Davidson & Co',
 'Daiwa Securities',
 'Drexel Hamilton LLC',
 'Evercore ISI',
 'FBR Capital Markets',
 'First Global Stockbroking',
 'GMP',
 'Goldman Sachs',
 'Griffin Securities',
 'Guggenheim Securities',
 'HSBC',
 'ISI Group',
 'Iberia Capital Partners LLC',
 'Independent II Research plc',
 'J.P. Morgan',
 'Jefferies',
 'KLR Group',
 'Loop Capital Markets',
 'Macquarie',
 'Madison Williams',
 'Miller Tabak + Co., LLC',
 'Morgan Keegan',
 'Morgan Stanley',
 'Nomura',
 'Nomura Instinet',
 'Oppenheimer & Co',
 'Oracle Investment Research',
 'Piper Jaffray',
 'Pritchard Capital Partners LLC',
 'RBC Capital Markets',
 'Raymond James',
 'S&P Capital IQ',
 'Scotia Howard Weil Inc',
 'Seaport Global Securities',
 'Societe Generale',
 'Soleil Securities',
 'Stephens Inc',
 'Sterne Agee CRT',
 'SunTrust Robinson Humphrey',
 'Susquehanna Financial',
 'Tristone Capital',
 'UBS',
 'Weeden & Co',
 'Wells Fargo Securities',
 'Wolfe Research',
 'Buckingham Research Group',
 'CIBC World Markets',
 'Collins Stewart',
 'Dresdner Kleinwort',
 'Keefe, Bruyette & Woods',
 'Lehman Brothers',
 'MF Global Equities Research',
 'Pali International',
 "Sandler O'Neill & Partners, LP",
 'Stifel',
 'Ticonderoga Securities LLC',
 'William Blair & Co',
 'A.G. Edwards & Sons Inc',
 'Aperion Group LLC',
 'Duncan Williams',
 'Jesup & Lamont',
 'KeyBanc Capital Markets',
 'MKM Partners',
 'Natixis Securities Americas LLC',
 'Peters & Co Ltd',
 'Brean Capital LLC',
 'CL King & Associates',
 'Exane BNP Paribas',
 'Lazard Capital Markets',
 'Northcoast Research',
 'Sidoti & Company LLC',
 'Telsey Advisory Group',
 'Topeka Capital Markets Inc',
 'Value Investment Principals',
 'Fox-Pitt Kelton Cochran Caronia Waller',
 'JMP Securities',
 'Arctic Securities ASA',
 'DNB Markets',
 'Davenport & Co',
 'Fearnley Securities',
 'Nordea',
 'Pareto Securities',
 'SpareBank 1 Markets AS',
 'Spin-Off Research',
 'Stanford Group',
 'Swedbank',
 'Wunderlich Securities',
 'Cross Research',
 'Janney Montgomery Scott LLC',
 'Longbow Research',
 'Thomas Weisel Partners',
 'Avondale Partners LLC',
 'Dougherty & Company LLC',
 'FTN Equity Capital Markets Corp.',
 'GC Research Ltd',
 'Gleacher & Company',
 'Morgan Joseph TriArtisan Group',
 'Needham & Co',
 'Pacific Crest Securities',
 'Phillip Securities',
 'Wedbush',
 'Williams Financial Group',
 'Williams Capital',
 'BOE Securities',
 'Johnson Rice & Co',
 'Benchmark Company LLC',
 'CM Research',
 'Cantor Fitzgerald',
 'Northland Securities Inc',
 'Pivotal Research Group LLC',
 'Kevin Dann & Partners',
 'Langenberg & Co',
 'Prudential Equity Group Inc',
 'ThinkEquity LLC',
 'BB&T Capital Markets',
 'Berenberg',
 'Kaufman Bros',
 'Monness, Crespi, Hardt & Co',
 'Moors & Cabot',
 'Rochdale Securities',
 'AURIGA',
 'BTIG LLC',
 'CRT Capital Group',
 'Capstone Investments Inc.',
 'Caris & Company',
 'Craig-Hallum Capital Group LLC',
 'FBN Securities',
 'Hapoalim Securities USA',
 'Knight',
 'Maxim Group LLC',
 'Mizuho Securities USA Inc',
 'Noble Financial Group',
 'Oscar Gruss & Son Inc',
 'WR Hambrecht + Co',
 'Vertical Research Partners',
 'WhiteSand Research LLC',
 'Leerink Partners LLC',
 'Aegis Capital Corp.',
 'Jyske Bank',
 'Imperial Capital LLC',
 'B Riley & Co',
 'Barrington Research',
 'Makor Capital',
 'Broadpoint Capital, Inc',
 'Roth Capital Partners',
 'Summer Street Research Partners',
 'Boenning & Scattergood Inc',
 'Ladenburg Thalmann & Co',
 'McAdams Wright Ragen Inc',
 'Rodman & Renshaw',
 'Sturdivant & Co',
 'R.W. Pressprich & Co',
 'ABG Sundal Collier',
 'Beringer Finance',
 'Citadel Securities LLC',
 'Guzman & Company',
 'Handelsbanken',
 'Hudson Securities Inc',
 'SEB Equities',
 'Alembic Global Advisors',
 'BWS Financial',
 'Tudor Pickering & Co',
 'Avian Securities, LLC',
 'Rosenblatt Securities',
 'Scotia Capital',
 'US Capital Advisors',
 'Churchill Research',
 'VTB Capital',
 'Hilliard Lyons',
 'Hudson Square Research',
 'Independent Research GmbH',
 'Janco Partners Inc',
 'MoffettNathanson',
 'National Bank Financial',
 'New Street Research',
 'Cathay Financial',
 'Ascendiant Capital Markets',
 'Consumer Edge Research',
 'Nollenberger Capital',
 'Thompson Research Group',
 'Murphy & Durieu LP',
 'National Securities',
 'BGC Partners',
 'First Analysis Corp',
 'Greenwich Consultants LLC',
 'CJS Securities',
 'MUFG Securities Americas, Inc',
 'Ryan Beck & Co',
 'MP Advisors',
 'Great Lakes Review',
 'Wall Street Access',
 'Compass Point Research & Trading LLC',
 'Cochran Caronia Waller',
 'Axiom Capital',
 'Blaylock Beal Van LLC',
 'Freedom Finance',
 'Jackson Securities LLC',
 'ROE Equity Research',
 'Renaissance Macro Research LLC',
 'Ardour Capital',
 'TD Securities',
 'ICAP',
 'Prime Executions',
 'MLV & Co',
 'ACI Research',
 'Accountability Research Corp',
 'Crowell, Weedon & Co',
 'Dolmen Stockbrokers',
 'High Technology Invest',
 'Summit Research Partners LLC',
 'Rafferty Capital Markets',
 'Vertical Group',
 'Millman Research Associates',
 'FIG Partners LLC',
 'Vining Sparks',
 'Coker & Palmer',
 'Wm Smith & Co',
 'JSA Research Inc',
 'BGB Securities Inc.',
 'Feltl & Company',
 'Thompson, Davis & Co',
 'Albert Fried & Company',
 'Tradition Asiel Securities Inc.',
 'Wallachbeth Capital LLC',
 'The Juda Group',
 'National Bank AG',
 'Renaissance Capital',
 'Gilford Securities',
 'Eight Capital',
 'Axon Securities',
 'Desjardins Securities',
 'Mediobanca SpA',
 'Meredith Whitney Advisory Group',
 'ERA Forest Products Research',
 'Salman Partners',
 'Veritas Investment Research Co',
 'Mackie Research Capital Corp.']

In [117]:
#analysts_universe = list(set(analysts_universe))
reduced_rec_data = defaultdict()
for ticker in rec_data.keys():
    try:
        reduced_rec_data[ticker] = rec_data[ticker][rec_data[ticker]["Firm Name"].isin(analysts_universe)].copy()
    except:
        reduced_rec_data[ticker] = pd.DataFrame(columns= ["Date", "Firm Name", "Target Price"])

In [118]:
reduced_rec_data[ticker]

           Date                    Firm Name  Target Price
3    2005-08-17                Credit Suisse          45.0
6    2005-11-18            Bear Stearns & Co          39.0
7    2005-11-23              Lehman Brothers          39.0
8    2005-11-28               Morgan Stanley          40.0
9    2005-12-01                       Stifel          38.0
10   2005-12-05                          UBS          37.0
11   2005-12-13  Prudential Equity Group Inc          41.5
12   2005-12-14                        Baird          35.5
14   2006-01-12  Prudential Equity Group Inc          41.5
16   2006-01-17              Lehman Brothers          39.0
17   2006-01-27                        Baird          39.0
18   2006-02-13            Bear Stearns & Co          40.5
19   2006-02-14               Morgan Stanley          45.0
20   2006-02-14  Prudential Equity Group Inc          41.5
21   2006-02-15                        Baird          40.0
22   2006-02-15              Lehman Brothers          47.5
23   2006-02-15                Credit Suisse          45.0
24   2006-02-15                       Stifel          42.0
25   2006-02-23  Prudential Equity Group Inc          41.5
26   2006-03-02                          UBS          38.5
27   2006-03-23                       Stifel          42.0
28   2006-03-27                Credit Suisse          51.5
29   2006-04-03                       Stifel          42.0
31   2006-04-12  Prudential Equity Group Inc          50.0
32   2006-04-18                          UBS          43.0
33   2006-04-27            Bear Stearns & Co          46.0
34   2006-04-27                       Stifel          55.5
35   2006-05-17                Credit Suisse          51.5
36   2006-05-17                          UBS          44.0
37   2006-05-17                        Baird          49.0
...         ...                          ...           ...
2592 2017-04-07                    Macquarie         102.0
2593 2017-04-10                       Stifel         126.0
2596 2017-04-10                  J.P. Morgan          90.0
2597 2017-04-10          RBC Capital Markets         109.0
2598 2017-04-11                    Jefferies         105.0
2599 2017-04-12                Credit Suisse         132.0
2601 2017-04-13                        Baird         125.0
2602 2017-04-13    Seaport Global Securities         102.0
2604 2017-04-17               Morgan Stanley          94.0
2605 2017-04-17          RBC Capital Markets         109.0
2606 2017-04-17                     Barclays          82.0
2609 2017-04-18                Piper Jaffray         106.0
2610 2017-04-20    Seaport Global Securities         102.0
2611 2017-04-24                Piper Jaffray         106.0
2613 2017-04-25          RBC Capital Markets         109.0
2615 2017-05-01          RBC Capital Markets         109.0
2616 2017-05-01                  J.P. Morgan          94.0
2617 2017-05-02                    Macquarie         102.0
2618 2017-05-03                    Macquarie         102.0
2619 2017-05-05                Piper Jaffray         106.0
2620 2017-05-05                 Evercore ISI         114.0
2621 2017-05-05    Seaport Global Securities         102.0
2626 2017-05-10          RBC Capital Markets         109.0
2627 2017-05-10                        Baird         125.0
2630 2017-05-15          RBC Capital Markets         109.0
2631 2017-05-15   Vertical Research Partners         115.0
2633 2017-05-15                  J.P. Morgan          95.0
2634 2017-05-16                        Baird         125.0
2635 2017-05-16                    Jefferies         105.0
2636 2017-05-17                  J.P. Morgan          95.0

[1933 rows x 3 columns]

In [119]:

# when we are at day t I want to consider recommendations no more than 30 days old
# so we need to calc when we should update targets
turn_points = defaultdict()
for ticker in tqdm.tqdm(list(reduced_rec_data.keys())):
    try:
        #print reduced_rec_data[ticker] 
        reduced_rec_data[ticker] = reduced_rec_data[ticker].loc[reduced_rec_data[ticker].Date <= market_data[ticker].index[-1]]
        buf = np.unique(reduced_rec_data[ticker]["Date"])

        # get nearest trading day after releasing analyst's rec
        #print buf[-1]
        #print market_data[ticker].index[-1]
        #print reduced_rec_data[ticker]
        #print market_data[ticker].index
        #print buf

        buf = list(map(lambda z: market_data[ticker].index[market_data[ticker].index >= z][0], buf))
        # skip 30 first days
        if (len(buf)==0):
            turn_points[ticker] = np.array(buf)
            continue
        buf = np.array(buf)[np.array(buf) > (buf[0] + datetime.timedelta(days = 30))]
        turn_points[ticker] = buf
    except:
        turn_points[ticker] = np.array([])

100%|████████████████████████████████████████████| 1/1 [00:00<00:00,  5.71it/s]

In [120]:
from sklearn.preprocessing import LabelEncoder
# encode analyst's firm names
le = LabelEncoder()
le.fit(analysts_universe)
for ticker in tqdm.tqdm(reduced_rec_data.keys()):    
    reduced_rec_data[ticker]["Firm Name"] = le.transform(reduced_rec_data[ticker]["Firm Name"])

100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 499.92it/s]

In [121]:
turn_points['US2441991054'] = [turn_points['US2441991054'][-1]]

In [122]:
market_data['US2441991054']

                Open     High       Low    Close
Date
2006-01-03   34.0050   34.215   33.9300   34.000
2006-01-04   34.0000   34.260   33.8050   34.045
2006-01-05   33.8250   34.155   33.8250   34.100
2006-01-06   34.2250   34.400   34.1550   34.215
2006-01-09   34.2150   34.560   34.1800   34.415
2006-01-10   34.3500   34.430   34.0100   34.430
2006-01-11   34.4300   34.705   34.1500   34.575
2006-01-12   34.6300   34.800   34.2600   34.640
2006-01-13   34.7500   34.830   34.5500   34.800
2006-01-17   34.5400   35.240   34.4900   35.195
2006-01-18   34.9750   35.265   34.9300   35.205
2006-01-19   35.3000   35.745   35.2150   35.235
2006-01-20   35.4050   35.410   34.4000   34.430
2006-01-23   34.4450   34.835   34.2550   34.600
2006-01-24   34.7150   35.585   34.6750   35.360
2006-01-25   35.3500   35.975   35.0400   35.785
2006-01-26   35.9000   36.000   35.2000   35.675
2006-01-27   35.6750   36.300   35.6000   36.200
2006-01-30   36.1250   36.280   35.8400   36.110
2006-01-31   36.1150   36.115   35.6800   35.880
2006-02-01   35.8925   37.965   34.9050   37.550
2006-02-02   37.5300   37.745   37.2600   37.370
2006-02-03   37.3800   37.505   37.0750   37.255
2006-02-06   37.2550   37.500   36.9800   37.460
2006-02-07   37.4765   37.720   37.2950   37.545
2006-02-08   37.5000   37.505   36.4000   36.785
2006-02-09   36.8030   37.290   36.6000   36.935
2006-02-10   36.9500   37.045   36.4450   36.810
2006-02-13   36.8250   37.190   36.6450   36.900
2006-02-14   36.7400   37.670   35.8500   37.335
...              ...      ...       ...      ...
2017-04-06  109.6200  110.890  109.2000  110.440
2017-04-07  110.3800  110.840  109.2900  109.320
2017-04-10  109.4500  110.210  109.1800  109.630
2017-04-11  110.0200  111.380  109.3700  111.160
2017-04-12  110.9900  111.199  109.2800  109.350
2017-04-13  109.1000  109.570  107.9600  108.000
2017-04-17  108.3900  108.990  107.7500  108.800
2017-04-18  108.0200  108.880  107.8300  108.470
2017-04-19  108.8000  108.990  107.8900  108.220
2017-04-20  108.0000  109.150  107.2600  108.800
2017-04-21  109.0400  109.470  107.0400  107.540
2017-04-24  109.0100  110.590  108.9400  110.250
2017-04-25  111.6800  114.130  111.5700  113.150
2017-04-26  113.0900  113.780  112.5000  112.550
2017-04-27  112.5000  112.680  110.5400  111.180
2017-04-28  111.0000  111.855  109.8400  111.610
2017-05-01  112.2500  112.790  111.9300  111.970
2017-05-02  112.2800  112.943  110.4200  110.930
2017-05-03  110.3400  111.000  109.7900  110.790
2017-05-04  111.0200  112.090  110.4200  112.030
2017-05-05  111.6000  113.140  111.3800  113.110
2017-05-08  112.9400  113.130  112.2200  112.640
2017-05-09  112.9600  114.040  112.8400  113.580
2017-05-10  113.5000  114.170  113.3300  113.550
2017-05-11  113.4500  114.130  112.2900  113.470
2017-05-12  113.0400  113.180  112.3700  113.110
2017-05-15  113.6200  113.970  113.2700  113.800
2017-05-16  114.1000  114.960  113.8254  114.800
2017-05-17  113.8000  114.460  113.0500  113.230
2017-05-18  112.1900  113.040  111.1200  112.310

[2864 rows x 4 columns]

In [123]:
debug = True
# Prepare data for StrategyBaker
features_data = defaultdict()
for ticker in tqdm.tqdm(tickers):
    try:
        features_data[ticker] = pd.DataFrame(np.zeros(shape = (len(np.unique(turn_points[ticker])), len(analysts_universe))),
                                             index = np.unique(turn_points[ticker]))
        features_data[ticker].index.name = "Date"
        for day_ in np.unique(turn_points[ticker]):
            # when we are at day t I want to consider recommendations no more than 30 days old
            day_in_past = day_ - datetime.timedelta(days = 30)
            indxs = (reduced_rec_data[ticker]["Date"] <= day_) & (reduced_rec_data[ticker]["Date"] >= day_in_past)
            actual_recs = reduced_rec_data[ticker].loc[indxs]

            for firm_id, target_price in zip(actual_recs["Firm Name"], actual_recs["Target Price"]):
                features_data[ticker].loc[day_][firm_id] = target_price

        df = pd.concat([features_data[ticker], market_data[ticker]], axis = 1).ffill().dropna()
        df = df[df.index >= datetime.datetime(2006, 1, 1)]
        mdf = market_data[ticker].loc[ market_data[ticker].index >= df.index[0] ]
        # to make all the assets comparable let's calc percent distance between target and price every day



        for day_ in df.index:
            vec = df.loc[day_]
            count = float(len(vec[vec != 0.]) - 4)
            for i in range(0, len(vec)):
                if vec[i] != 0:
                    vec[i] = (vec[i] - vec[-1]) / vec[-1] / count

            df.loc[day_] = vec

        features_data[ticker] = df.drop(["Open", "High", "Low", "Close"], axis = 1)
        market_data[ticker] = mdf
        
        
        if debug == True:
            print(features_data[ticker].sum(axis=1))
            print(mdf)
            print(actual_recs)
            raise NotImplemented
    except:
        print(ticker)
        features_data[ticker] = pd.DataFrame()

  0%|                                                    | 0/1 [00:00<?, ?it/s]

Date
2017-05-17   -0.077501
2017-05-18   -0.069944
dtype: float64
              Open    High     Low   Close
Date
2017-05-17  113.80  114.46  113.05  113.23
2017-05-18  112.19  113.04  111.12  112.31
           Date  Firm Name  Target Price
2604 2017-04-17        155          94.0
2605 2017-04-17        184         109.0
2606 2017-04-17         27          82.0
2609 2017-04-18        178         106.0
2610 2017-04-20        201         102.0
2611 2017-04-24        178         106.0
2613 2017-04-25        184         109.0
2615 2017-05-01        184         109.0
2616 2017-05-01        111          94.0
2617 2017-05-02        140         102.0
2618 2017-05-03        140         102.0
2619 2017-05-05        178         106.0
2620 2017-05-05         76         114.0
2621 2017-05-05        201         102.0
2626 2017-05-10        184         109.0
2627 2017-05-10         26         125.0
2630 2017-05-15        184         109.0
2631 2017-05-15        235         115.0
2633 2017-05-15        111          95.0
2634 2017-05-16         26         125.0
2635 2017-05-16        117         105.0
2636 2017-05-17        111          95.0
US2441991054

100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 19.61it/s]

In [21]:
data = pd.DataFrame()
for sym in tqdm.tqdm(tickers):    
    data = pd.concat([data, features_data[sym].sum(axis=1)], axis=1)

100%|████████████████████████████████████████| 768/768 [00:11<00:00, 66.75it/s]

In [22]:
market_data_table = pd.read_csv('../un_spx_daily_nonadjusted_close.csv', parse_dates=['Date'], index_col='Date')

In [25]:
market_data_table.tail()

,AN8068571086,BMG491BT1088,BMG6359F1032,BMG812761002,BMG982941046,CH0044328745,CH0048265513,CH0102993182,CH0114405324,GB00B4VLR192,...,US98389B1008,US9839191015,US9841211033,US98419M1009,US9843321061,US9884981013,US98956P1021,US9897011071,US98978V1035,VGG607541015
Date,,,,,,,,,,,,,,,,,,,,,
2017-05-12,71.0200,32.12,9.600,60.13,41.86,136.74,10.6200,75.67,52.1500,7.650,...,45.58,64.300,7.050,50.98,49.65,68.90,121.26,40.15,59.88,36.74
2017-05-15,72.0000,32.22,10.040,60.19,41.92,137.37,10.8000,75.99,52.3900,7.770,...,45.81,64.790,7.150,52.29,49.86,69.22,122.33,40.54,60.00,36.47
2017-05-16,71.3700,32.18,10.110,58.52,42.01,137.02,10.6900,76.43,52.6000,7.740,...,45.57,65.460,7.140,51.77,50.96,69.35,119.78,40.66,60.33,35.95
2017-05-17,70.9900,30.66,9.660,58.90,41.79,137.79,10.3900,73.95,51.1000,7.400,...,45.61,64.760,6.880,51.55,49.65,69.16,117.72,38.99,59.73,35.82
2017-05-18,71.5196,31.00,9.795,59.39,42.07,138.63,10.5481,73.40,51.0857,7.535,...,45.52,65.465,6.995,51.55,49.02,69.14,117.20,39.43,60.02,35.71

In [26]:
ideal = market_data_table.ix[:, 0]
ideal.name= 'ideal'
cdata = pd.concat([ideal, data], axis=1).drop('ideal', axis=1)

In [27]:
cdata.to_csv('../Features/RA_factor.csv')

In [28]:
cdata

,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Date,,,,,,,,,,,,,,,,,,,,,
2006-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-03,NaN,NaN,NaN,NaN,NaN,NaN,0.243830,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-06,NaN,NaN,NaN,NaN,0.145833,NaN,0.231145,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.194403,NaN,NaN,NaN
2006-02-07,NaN,NaN,0.344694,NaN,0.142772,NaN,0.295422,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.097636,0.184458,NaN,NaN,NaN
2006-02-08,NaN,NaN,0.304443,NaN,0.152746,NaN,0.301481,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.076397,0.177978,NaN,NaN,NaN
2006-02-09,NaN,NaN,0.352026,NaN,0.148927,NaN,0.331783,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.309615,0.091689,0.163867,0.065527,NaN,NaN
2006-02-10,NaN,NaN,0.358869,NaN,0.144931,NaN,0.305276,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.309213,0.074466,0.149705,0.055670,NaN,NaN
2006-02-13,NaN,NaN,0.369171,NaN,0.147708,NaN,0.310092,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.328418,0.074036,0.147862,0.066065,NaN,NaN
2006-02-14,NaN,NaN,0.415005,NaN,0.141651,NaN,0.390622,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.300810,0.064051,0.146693,0.046643,NaN,NaN
2006-02-15,NaN,NaN,0.411565,NaN,0.140275,NaN,0.401232,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.288992,0.063419,0.151385,0.043668,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-04-06,0.232626,0.144165,0.025247,0.252675,0.055276,0.069300,0.138249,0.157160,-0.001597,0.008691,...,-0.019639,-0.023784,0.150070,0.074083,-0.022256,0.141234,0.188644,0.119555,0.162374,-0.001888
2017-04-07,0.237190,0.152453,0.032747,0.240181,0.054746,0.066091,0.158488,0.159063,-0.007346,0.024090,...,-0.015444,-0.026204,0.151685,0.075985,-0.025624,0.146028,0.176176,0.121663,0.165250,-0.014647
2017-04-10,0.228907,0.138211,0.012018,0.231870,0.036694,0.063560,0.135871,0.151020,-0.010685,0.004375,...,-0.010206,-0.017682,0.158192,0.077893,0.011438,0.142211,0.174706,0.123870,0.160831,-0.007777
2017-04-11,0.212692,0.152223,-0.004397,0.244196,0.026202,0.064949,0.151459,0.154318,0.000200,0.005451,...,0.011664,-0.017155,0.158192,0.082419,0.020517,0.141855,0.176339,0.123596,0.128193,-0.020127
2017-04-12,0.215227,0.164698,0.041124,0.261082,0.038052,0.065538,0.195342,0.168186,0.014405,0.076939,...,0.004454,-0.001815,0.166430,0.110696,0.019646,0.130720,0.180387,0.139898,0.120349,-0.020646
2017-04-13,0.237308,0.182151,0.100362,0.268270,0.046613,0.067876,0.211155,0.176143,0.026905,0.127360,...,0.021547,-0.012213,0.166430,0.129588,0.010661,0.134974,0.176831,0.161280,0.128060,-0.014909
2017-04-17,0.230328,0.138952,0.109006,0.263532,0.029629,0.056516,0.204986,0.162567,0.020825,0.132800,...,0.015655,0.016515,0.157407,0.116342,0.044524,0.133198,0.166502,0.140182,0.119626,-0.008574
2017-04-18,0.229736,0.142298,0.125809,0.283868,0.056629,0.037355,0.219479,0.156267,0.015022,0.128715,...,0.015204,0.009028,0.157407,0.123841,0.066322,0.131957,0.177135,0.150201,0.118581,0.024390
2017-04-19,0.253051,0.128668,0.180405,0.277853,0.056367,0.041369,0.250175,0.154687,0.008471,0.146631,...,0.017020,0.004759,0.170749,0.122180,0.100000,0.121785,0.170381,0.145885,0.112349,0.025224
2017-04-20,0.252560,0.110406,0.199460,0.254347,0.057152,0.042816,0.238091,0.140043,0.000400,0.132800,...,0.020437,-0.012303,0.165710,0.102293,0.092740,0.093832,0.155109,0.115202,0.103334,0.005854
2017-04-21,0.275499,0.118926,0.197426,0.278433,0.055844,0.052822,0.246856,0.147942,0.001001,0.128715,...,0.019902,-0.011960,0.174133,0.092935,0.096189,0.105626,0.155211,0.121481,0.105165,0.028292
2017-04-24,0.251338,0.092726,0.200480,0.279207,0.040650,0.042816,0.244503,0.123521,-0.005767,0.117965,...,0.008441,-0.012549,0.150850,0.068584,0.083735,0.082515,0.141397,0.087871,0.113839,0.064120
2017-04-25,0.245216,0.087970,0.199460,0.264477,0.024902,0.036915,0.224855,0.093474,-0.014584,0.124660,...,0.008665,-0.013017,0.180258,0.061571,0.078137,0.078249,0.123128,0.148432,0.118771,0.040833
2017-04-26,0.244880,0.078915,0.202525,0.256024,0.025519,0.048490,0.225925,0.108937,-0.011272,0.106114,...,0.012489,0.007860,0.177062,0.068999,0.081264,0.079886,0.115689,0.129189,0.109711,0.017458
2017-04-27,0.263500,0.082643,0.338166,0.275925,0.016080,0.055363,0.269154,0.083629,-0.023628,0.179762,...,0.012227,-0.043661,0.173756,0.065478,0.071822,0.077759,0.164268,0.143630,0.092219,0.018529
2017-04-28,0.267851,0.081512,0.365343,0.284258,0.041816,0.066555,0.286038,0.078306,-0.085366,0.190229,...,0.018061,-0.024113,0.162329,0.069831,0.075157,0.082021,0.156150,0.161629,0.099032,0.037082
2017-05-01,0.272476,0.089783,0.392273,0.292898,0.039545,0.073333,0.321295,0.087726,-0.102836,0.234022,...,0.025856,-0.020588,0.183731,0.071707,0.064128,0.082021,0.136505,0.143468,0.095712,0.054311
2017-05-02,0.286214,0.092456,0.414594,0.287387,0.045487,0.072237,0.351727,0.103261,-0.004684,0.274207,...,0.025627,-0.010120,0.187094,0.098138,0.053723,0.074013,0.139331,0.158913,0.084647,0.021485
2017-05-03,0.284776,0.090450,0.413178,0.300655,0.038316,0.068105,0.309015,0.111344,-0.003552,0.253793,...,0.027921,-0.008856,0.200739,0.109459,0.065663,0.068132,0.150779,0.141778,0.101817,0.041266
2017-05-04,0.295461,0.099198,0.489203,0.323248,0.032941,0.062390,0.339942,0.102823,-0.031505,0.307926,...,0.023115,-0.014052,0.205937,0.080024,0.067642,0.066734,0.176187,0.139251,0.039956,0.032106
2017-05-05,0.276921,0.100216,0.386802,0.300655,0.036110,0.066632,0.213736,0.105746,-0.051248,0.194772,...,0.020163,-0.021051,0.182057,0.063917,0.066762,0.064214,0.179316,0.137014,0.032453,0.016123
2017-05-08,0.272501,0.101236,0.440576,0.311752,0.047733,0.070674,0.218378,0.100350,-0.041570,0.199350,...,0.018354,-0.018849,0.175407,0.065955,0.058900,0.069087,0.175584,0.124595,0.044040,0.012403
2017-05-09,0.271444,0.094134,0.423150,0.301856,0.045238,0.077821,0.238388,0.100496,-0.042492,0.199350,...,0.026543,-0.020669,0.187094,0.073151,0.042298,0.074995,0.158246,0.132014,0.041562,0.001663
2017-05-10,0.264621,0.099877,0.384083,0.341300,0.046733,0.064700,0.215105,0.094002,-0.053592,0.165125,...,0.023799,-0.019608,0.177062,0.090181,0.044197,0.064281,0.150201,0.131738,0.033389,0.012668
2017-05-11,0.280301,0.108087,0.430359,0.370875,0.049235,0.070830,0.224975,0.090997,-0.048892,0.179762,...,0.017903,-0.019001,0.180387,0.093610,0.038103,0.051848,0.135659,0.146865,0.036504,0.041266
2017-05-12,0.294002,0.109122,0.470588,0.406212,0.057638,0.077283,0.278035,0.102532,-0.045062,0.227570,...,0.008300,-0.014729,0.185410,0.091464,0.038939,0.055360,0.133412,0.154006,0.033734,0.053737
2017-05-15,0.276389,0.105680,0.406140,0.295896,0.056124,0.072343,0.254428,0.097889,-0.049437,0.208611,...,0.005140,-0.022180,0.168831,0.075048,0.034563,0.050481,0.123498,0.142904,0.031667,0.083082
2017-05-16,0.287656,0.107054,0.396404,0.332878,0.053862,0.075082,0.267336,0.091568,-0.053232,0.213296,...,0.010433,-0.032188,0.170468,0.085847,0.018773,0.055516,0.125102,0.139531,0.026024,0.098748
2017-05-17,0.294549,0.161937,0.461454,0.324278,0.059410,0.069074,0.303929,0.128175,-0.025440,0.269042,...,0.009547,-0.021727,0.214701,0.090481,0.045653,0.058415,0.144790,0.188339,0.036330,0.102736
2017-05-18,0.284962,0.149194,0.441312,0.313352,0.052359,0.062596,0.284385,0.136629,-0.025168,0.246305,...,0.011543,-0.032262,0.194731,0.090481,0.059092,0.058721,0.149870,0.175078,0.031323,0.106133

In [ ]:
cdata.shape

In [38]:
data.columns = tickers
data.tail().to_csv('D:/raf.csv')